export const UPDATE_SERVICE = 'UPDATE_SERVICE';

export const SET_ACTIVE_SERVICE = 'SET_ACTIVE_SERVICE';

export const SET_CONVERSION_AMOUNT = 'SET_CONVERSION_AMOUNT';

export const SET_FAVORITE_CODES = 'SET_FAVORITE_CODES';
